### ISSUE TITLE
Precompile error - Julia v0.7/1.0 compatibility

### ISSUE THREAD

**Issue by migarstka** [JuliaSmoothOptimizers/AMD.jl#13]
When I 
```
add AMD#master
using AMD
```
try to precompile the package under Julia v0.7/1.0 I get the following error:
```
ERROR: LoadError: syntax: extra token "Amd" after end of expression
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include(::Module, ::String) at ./sysimg.jl:29
 [4] top-level scope at none:2
 [5] eval at ./boot.jl:319 [inlined]
 [6] eval(::Expr) at ./client.jl:389
 [7] top-level scope at ./none:3
in expression starting at /~/.julia/packages/AMD/k9NUS/src/AMD.jl:59
```

**Comment by dpo** [comment]
Thank you for the report. There's more to update than a few points of syntax to get things going in Julia 0.7. I'm looking into it.

**Comment by dpo** [comment]
Should be fixed by #14.

**Comment by migarstka** [comment]
I still get the same error when trying to precompile from master. It seems because you are still using the deprecated type definition (instead of struct) here: https://github.com/JuliaSmoothOptimizers/AMD.jl/blob/87b7494c6e2c6c71ea621f6e59cab6997b6915cb/src/AMD.jl#L59

**Comment by dpo** [comment]
Sorry. Reopening.

**Comment by dpo** [comment]
Try using the master branch. Or wait until a new released is pushed (which should be shortly).

**Comment by abelsiqueira** [comment]
Just a heads up, it works on 0.7, not on 1.0 yet.

**Comment by dpo** [comment]
New release support 0.7 is out. Could you confirm whether it works for you?

**Comment by migarstka** [comment]
So when I pull the newest master branch, I can precompile under Julia v0.7 with some deprecations warnings:
```julia
Recompiling stale cache file /~/.julia/compiled/v0.7/AMD/uxZ7x.ji for AMD [14f7f29c-3bd6-536c-9a0b-7339e30b5a3e]
┌ Warning: `global const` declarations may no longer appear inside functions.
│ Instead, use a non-constant global, or a global `const var = Ref{T}()`.
└ @ ~/.julia/packages/AMD/JKwp2/src/amd_functions.jl:8
┌ Warning: `global const` declarations may no longer appear inside functions.
│ Instead, use a non-constant global, or a global `const var = Ref{T}()`.
└ @ ~/.julia/packages/AMD/JKwp2/src/amd_functions.jl:10
┌ Warning: `global const` declarations may no longer appear inside functions.
│ Instead, use a non-constant global, or a global `const var = Ref{T}()`.
└ @ ~/.julia/packages/AMD/JKwp2/src/amd_functions.jl:11
┌ Warning: `global const` declarations may no longer appear inside functions.
│ Instead, use a non-constant global, or a global `const var = Ref{T}()`.
└ @ ~/.julia/packages/AMD/JKwp2/src/amd_functions.jl:12
┌ Warning: `global const` declarations may no longer appear inside functions.
│ Instead, use a non-constant global, or a global `const var = Ref{T}()`.
└ @ ~/.julia/packages/AMD/JKwp2/src/amd_functions.jl:14
┌ Warning: `global const` declarations may no longer appear inside functions.
│ Instead, use a non-constant global, or a global `const var = Ref{T}()`.
└ @ ~/.julia/packages/AMD/JKwp2/src/amd_functions.jl:15
┌ Warning: `global const` declarations may no longer appear inside functions.
│ Instead, use a non-constant global, or a global `const var = Ref{T}()`.
└ @ ~/.julia/packages/AMD/JKwp2/src/amd_functions.jl:16
WARNING: importing deprecated binding Base.Void into AMD.
WARNING: Base.Void is deprecated, use Nothing instead.
  likely near /Users/~/.julia/packages/AMD/JKwp2/src/AMD.jl:48
WARNING: importing deprecated binding Base.SparseMatrixCSC into AMD.
WARNING: Base.SparseMatrixCSC is deprecated, run `using SparseArrays` to load sparse array functionality
  likely near /Users/~/.julia/packages/AMD/JKwp2/src/AMD.jl:111
WARNING: Base.SparseMatrixCSC is deprecated, run `using SparseArrays` to load sparse array functionality
  likely near /Users/~/.julia/packages/AMD/JKwp2/src/AMD.jl:111
WARNING: Base.SparseMatrixCSC is deprecated, run `using SparseArrays` to load sparse array functionality
  likely near /Users/~/.julia/packages/AMD/JKwp2/src/AMD.jl:128
WARNING: Base.SparseMatrixCSC is deprecated, run `using SparseArrays` to load sparse array functionality
  likely near /Users/~/.julia/packages/AMD/JKwp2/src/AMD.jl:128
WARNING: Base.SparseMatrixCSC is deprecated, run `using SparseArrays` to load sparse array functionality
  likely near /Users/~/.julia/packages/AMD/JKwp2/src/AMD.jl:150
```

Precompiling under Julia v1.0 still causes errors:
```julia
ERROR: LoadError: LoadError: syntax: `global const` delcaration not allowed inside function around /Users/~/.julia/packages/AMD/JKwp2/src/amd_functions.jl:8
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include at ./sysimg.jl:29 [inlined]
 [4] include(::String) at /Users/~/.julia/packages/AMD/JKwp2/src/AMD.jl:1
 [5] top-level scope at none:0
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:319 [inlined]
 [11] eval(::Expr) at ./client.jl:389
 [12] top-level scope at ./none:3
in expression starting at /Users/~/.julia/packages/AMD/JKwp2/src/amd_functions.jl:7
in expression starting at /Users/~/.julia/packages/AMD/JKwp2/src/AMD.jl:46
```

**Comment by dpo** [comment]
yes, we don't support 1.0 yet.

**Comment by dpo** [comment]
Please feel free to close the issue if you feel it's resolved. We'll support Julia 1.0 after we've phased out 0.6.

**Comment by dpo** [comment]
Julia 1.0 support follows from #18.

**Comment by migarstka** [comment]
Great work! Thank you
